language : node_js

node_js:
 - "8"

os:
 - linux

stages:
 - name: deploy

jobs:
 include:

   - stage: deploy
     script:
       - echo "NPM Deploying Started ..."
       - npm version
       - npm run build-lib
       - echo "NPM Building-bundle Finished."

     deploy:
       provider: npm
       email: guzhao593@163.com
       api_key: "$NPM_TOKEN"
       skip_cleanup: true
       on:
         all_branches: true